name: Build and Deploy to Docker Hub and EC2

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: fastapi-app
  AWS_REGION: ap-northeast-2

permissions:
  contents: read

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      # (1) 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # (2) Python 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # (3) Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # (4) Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        run: |
          docker build --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      # (5) EC2 인스턴스에 SSH 접속하여 Docker 이미지 pull 및 run
      - name: SSH to EC2 and deploy Docker image
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_EC2_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            sudo docker stop fastapi-app || true
            sudo docker rm fastapi-app || true
            sudo docker run -d -p 8000:8000 --name fastapi-app -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
